// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVb499TlsFLdnW_IxLpmcJXZ_wVXUGPBM',
    appId: '1:437670893013:web:23a54b21dda9605e90d95c',
    messagingSenderId: '437670893013',
    projectId: 'phone-authentication-6f2ba',
    authDomain: 'phone-authentication-6f2ba.firebaseapp.com',
    storageBucket: 'phone-authentication-6f2ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDouc4Nf1CjDEcIqUUVGVuwLJ8S6mai2ZY',
    appId: '1:437670893013:android:127f9229c9f65d2d90d95c',
    messagingSenderId: '437670893013',
    projectId: 'phone-authentication-6f2ba',
    storageBucket: 'phone-authentication-6f2ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpEUfiDhODh0W9LaYE8P9koLySegNvQXw',
    appId: '1:437670893013:ios:8f7e936f732de9b990d95c',
    messagingSenderId: '437670893013',
    projectId: 'phone-authentication-6f2ba',
    storageBucket: 'phone-authentication-6f2ba.appspot.com',
    iosClientId: '437670893013-vvireotv99hhvha691bqo4ohf4u1ter6.apps.googleusercontent.com',
    iosBundleId: 'com.example.phone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpEUfiDhODh0W9LaYE8P9koLySegNvQXw',
    appId: '1:437670893013:ios:8f7e936f732de9b990d95c',
    messagingSenderId: '437670893013',
    projectId: 'phone-authentication-6f2ba',
    storageBucket: 'phone-authentication-6f2ba.appspot.com',
    iosClientId: '437670893013-vvireotv99hhvha691bqo4ohf4u1ter6.apps.googleusercontent.com',
    iosBundleId: 'com.example.phone',
  );
}
